-- Table: public.accounts

-- DROP TABLE public.accounts;

CREATE TABLE public.accounts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    details text COLLATE pg_catalog."default",
    balance money NOT NULL,
    created_at timestamp with time zone NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    CONSTRAINT accounts_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.accounts
    OWNER to postgres;
COMMENT ON TABLE public.accounts
    IS 'Table to manage the accounts';